- name: Deploy Networking Stack
  hosts: all
  gather_facts: true

  tasks:
    - name: Openshift Service
      ansible.builtin.include_tasks:
        file: tasks/openshift_service.yml
    - name: OpenShift Network Policy
      ansible.builtin.include_tasks:
        file: tasks/openshift_network.yaml
    
