---
- name: Create  service
  CHANGE_ME:
    state: present
    namespace: CHANGE_ME
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana
      spec:
        selector:
          CHANGE_ME
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: CHANGE_ME
