- name: Create redis netpol
  CHANGE_ME:
    state: present
    namespace: CHANGE_ME
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: allow-redis
      spec:
        podSelector:
          matchLabels:
            CHANGE_ME
        ingress:
          - ports:
              - protocol: TCP
                port: CHANGE_ME
